# Cards available at king poring.
gray = ["Poring Card", "Lunatic Card", "Fabre Card", "Thief Bug Card", "Familiar Card", "Male Thief Bug Card",
        "Chon Chon Card", "Rocker Card", "Willow Card", "Roda Frog Card", "Poison Spore Card", "Vadon Card",
        "Marina Card", "Obeaune Card", "Goblin Card", "Flora Card", "Andre Card", "Muka Card", "Mummy Card",
        "Isis Card", "Bigfoot Card", "Horong Card", "Munak Card", "Bongun Card", "Marduk Card", "Orc Warrior Card",
        "Orc Archer Card", "Marionette Card", "Sky Petite Card", "Injustice Card", "Sting Card", "Golem Card",
        "Weak Puppet Card", "Pupa Card", "Peco Peco Egg Card", "Picky Card", "Thief Bug Egg Card", "Mimic Card"]
green = ["Tarou Card", "Spore Card", "Female Thief Bug Card", "Yoyo Card", "Mandragora Flower Card", "Wolf Card",
         "Skeleton Card", "Marc Card", "Hornet Card", "Argiope Card", "Menblatt Card", "Drainliar Card", "Giearth Card",
         "Magnolia Card", "Matyr Card", "Elder Willow Card", "Greatest General Card", "Savage Card", "Sohee Card",
         "Dokebi Card", "Nine Tail Card", "High Orc Card", "Nightmare Card", "Orc Zombie Card", "Orc Skeleton Card",
         "Hunter Fly Card", "Green Petite Card", "Wraith Card", "Gargoyle Card", "Cramp Card", "Anolian Card",
         "Raydric Archer Card", "Khalitzburg Card", "Rideword Card", "Joker Card", "Wanderer Card", "Wild Rose Card",
         "Kobold Archer Card", "Dark Priest Card", "Punk Card", "Black Witch Card", "Ancient Clock Card", "Alarm Card",
         "Elder Card", "Brilight Card", "Orc Lady Card", "Metaller Card", "Gingerbread Man Card", "Myst Case Card",
         "Cruiser Card", "Zipper Bear Card", "Cookie Card", "Carat Card", "Meta Ant Egg Card"]
blue = ["Creamy Card", "Hydra Card", "Whisper Card", "Pirate Skeleton Card", "Thara Frog Card", "Phen Card",
        "Goblin Archer Card", "Steam Goblin Card", "Vitata Card", "Peco Peco Card", "Desert Wolf Card",
        "Soldier Skeleton Card", "Eggyra Card", "Minorous Card", "Archer Skeleton Card", "Deviruchi Card", "Ferus Card",
        "Succubus Card", "Incubus Card", "Raydric Card", "Wind Ghost Card", "Baphomet Jr. Card", "Kobold Card",
        "Mandragora Card", "Evil Druid Card", "Stem Worm Card", "Marine Sphere Card", "Swordfish Card", "Pasana Card",
        "Sandman Card", "Bathory Card", "Teddy Bear Card", "Aqua Elemental Card", "Draco Card", "Luciola Vespa Card",
        "Dark Shadow Card", "Dustiness Card", "Hode Card", "Marse Card", "Myst Card"]

# King poring gambling rates.
king_poring_rates = [
    {
        'Code': '300',
        'Input Colors': 'WWW',
        'White Chance': .195,
        'Green Chance': .8,
        'Blue Chance': .005,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '210',
        'Input Colors': 'WWG',
        'White Chance': .11,
        'Green Chance': .8,
        'Blue Chance': .09,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '120',
        'Input Colors': 'WGG',
        'White Chance': .07,
        'Green Chance': .75,
        'Blue Chance': .18,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '030',
        'Input Colors': 'GGG',
        'White Chance': 0,
        'Green Chance': .75,
        'Blue Chance': .25,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '201',
        'Input Colors': 'WWB',
        'White Chance': 0,
        'Green Chance': .65,
        'Blue Chance': .35,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '111',
        'Input Colors': 'WGB',
        'White Chance': 0,
        'Green Chance': .63,
        'Blue Chance': .37,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '021',
        'Input Colors': 'GGB',
        'White Chance': 0,
        'Green Chance': .60,
        'Blue Chance': .40,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '102',
        'Input Colors': 'WBB',
        'White Chance': 0,
        'Green Chance': .32,
        'Blue Chance': .68,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '012',
        'Input Colors': 'GBB',
        'White Chance': 0,
        'Green Chance': .3,
        'Blue Chance': .7,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
    {
        'Code': '003',
        'Input Colors': 'BBB',
        'White Chance': 0,
        'Green Chance': 0,
        'Blue Chance': 1,
        'Cost': None,
        'Expected Value': None,
        'Profit': None,
    },
]